from crewai import Task, Crew, Process
from agents import create_manager_agent, create_analyst_agent, create_reporter_agent
from tools import profile_csv_dataset, generate_plotly_chart_config, create_pdf_report
from typing import Dict, Any
import json

class AutoInsightCrew:
    """Coordinates multi-agent execution pipeline for CSV dataset analytics."""

    def __init__(self, file_path: str, user_query: str = ""):
        self.file_path = file_path
        self.user_query = user_query if user_query else "Provide a comprehensive data analysis and executive overview."
        
        # Instantiate Agents
        self.manager = create_manager_agent()
        self.analyst = create_analyst_agent()
        self.reporter = create_reporter_agent()

    def run(self) -> Dict[str, Any]:
        """
        Executes the CrewAI sequential workflow.
        
        Returns:
            Dict[str, Any]: Analysis result containing raw summary, executive text, and PDF output confirmation.
        """
        # Task 1: Dataset Profiling & Statistical Execution
        profiling_task = Task(
            description=f"""
            1. Use the 'CSV Data Profiler' tool on file path: '{self.file_path}'.
            2. Examine missing values, record counts, numerical summaries, and outlier bounds.
            3. Based on the columns, generate at least one relevant chart config using 'Plotly Chart Configurator'.
            4. User specific focus/question: '{self.user_query}'.
            """,
            expected_output="A structured report containing calculated dataset metrics and Plotly chart configuration JSON.",
            agent=self.analyst
        )

        # Task 2: Strategy & Insight Delegation Review
        orchestration_task = Task(
            description=f"""
            1. Review the data profiling metrics generated by the Data Analyst.
            2. Ensure all aspects of the user query ('{self.user_query}') are addressed.
            3. Synthesize key analytical themes and pass structured instructions to the Reporting Agent.
            """,
            expected_output="An analytical review outlining core business findings and narrative priorities.",
            agent=self.manager
        )

        # Task 3: Executive Summary & PDF Report Drafting
        reporting_task = Task(
            description=f"""
            1. Synthesize all findings from the Data Analyst and Manager into a polished Executive Brief.
            2. Include 3 distinct sections: 
               - Executive Summary & Key Highlights
               - Deep-Dive Data Insights & Anomaly Analysis
               - Strategic Recommendations & Actionable Next Steps
            3. Use the 'PDF Executive Summary Generator' tool to output a PDF report named 'reports/AutoInsight_Executive_Report.pdf'.
            """,
            expected_output="A full markdown executive brief and confirmation of generated PDF file.",
            agent=self.reporter
        )

        # Assemble Crew with Sequential Process
        crew = Crew(
            agents=[self.manager, self.analyst, self.reporter],
            tasks=[profiling_task, orchestration_task, reporting_task],
            process=Process.sequential,
            verbose=True
        )

        result = crew.kickoff()

        # Execute direct profiling for deterministic backend payload save
        raw_profiling_json = profile_csv_dataset.run(file_path=self.file_path)
        
        try:
            parsed_summary = json.loads(raw_profiling_json)
        except Exception:
            parsed_summary = {"raw": raw_profiling_json}

        return {
            "status": "completed",
            "data_summary": parsed_summary,
            "executive_report": str(result),
            "pdf_path": "reports/AutoInsight_Executive_Report.pdf"
        }
